### ISSUE TITLE
No suitable driver at ballerinax.java_jdbc:createClient when you try to connect with mysql

### ISSUE THREAD

**Issue by axewilledge** [ECLK/Results-Dist#110]
Modified the subscriber and included,

> import ballerinax/java.jdbc; 

to push data to mysql database which works fine in run method, but when you build

> ballerina build subscriber.bal

and try to run it with

> java -jar subscriber.jar "keyxxx"  -username"xxxxx" -password="xxxxx" -myURL="http://localhost:3000"

Following error comes,

> error: {ballerinax/java.jdbc}ApplicationError message=error in sql connector configuration: Failed to get driver instance for jdbcUrl=jdbc:mysql://localhost/election2019:No suitable driver       
>         at ballerinax.java_jdbc:createClient(jdbc_client.bal:87)
>            ballerinax.java_jdbc.Client:__init(client_endpoint.bal:27)
>            ..<init>(.:202)

**Comment by MaryamZi** [comment]
@axewilledge in order to pack the client JARs when creating the JAR, you will have switch to a Ballerina project, and mention the MySQL client dependency in the Ballerina.toml file.

Can you try the following steps:
1. Create a ballerina project
```cmd
$ ballerina new subscriber_project
```

This should result in the following structure.
```cmd
$ tree
.
└── subscriber_project
    ├── Ballerina.toml
    └── src

2 directories, 1 file
```

2. Go into the created folder and add a new Ballerina module.
```cmd
$ cd subscriber_project
$ ballerina add subscriber
```
This should result in the following structure.
```cmd
$ tree
.
├── Ballerina.toml
└── src
    └── subscriber
        ├── main.bal
        ├── Module.md
        ├── resources
        └── tests
            ├── main_test.bal
            └── resources

5 directories, 4 files
```

3. Move your logic into this module (you can just replace content of the main.bal file to start with)

4. Update the Ballerina.toml file specifying the dependency as follows
```toml
[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "mysql-connector-java"
    version = "5.1.40"
    path = "<PATH_TO_MYSQL_JAR>"
    groupId = "mysql"
    modules = ["subscriber"]
```

Modules should have the name of the module you added in 2. See https://github.com/ECLK/Results-Dist/blob/master/distributor/Ballerina.toml#L8 for an example.

5. Now run `ballerina build subscriber` from the subscriber_project to build the JAR.

**Comment by axewilledge** [comment]
That solution work like a charm. Thanks!
